### ISSUE TITLE
ImportError: No module named _backend_gdk

### ISSUE THREAD

**Issue by eadsjr** [vhernandez/jwsProcessor#4]
When attempting to execute the main module directly an import from matplotlib fails.

    >>> import main
    Traceback (most recent call last):
      File "<stdin>", line 1, in <module>
      File "main.py", line 17, in <module>
        from selection_page import SelectionPage
      File "selection_page.py", line 9, in <module>
        from smoothing_selection import ShowSpectrumPanel
      File "smoothing_selection.py", line 6, in <module>
        from matplotlib.backends.backend_gtk import FigureCanvasGTK as FigureCanvas
      File "/usr/local/lib/python2.7/site-packages/matplotlib/backends/backend_gtk.py", line 36, in <module>
        from matplotlib.backends.backend_gdk import RendererGDK, FigureCanvasGDK
      File "/usr/local/lib/python2.7/site-packages/matplotlib/backends/backend_gdk.py", line 33, in <module>
        from matplotlib.backends._backend_gdk import pixbuf_get_pixels_array
    ImportError: No module named _backend_gdk

After some more digging, it would appear that 'gdk' is available.

    >>> matplotlib.__version__
    '1.4.3'

    >>> matplotlib.get_backend()
    u'MacOSX'

    >>> matplotlib.rcsetup.all_backends
    [u'GTK', u'GTKAgg', u'GTKCairo', u'MacOSX', u'Qt4Agg', u'Qt5Agg', u'TkAgg', u'WX', u'WXAgg', u'CocoaAgg', u'GTK3Cairo', u'GTK3Agg', u'WebAgg', u'nbAgg', u'agg', u'cairo', u'emf', u'gdk', u'pdf', u'pgf', u'ps', u'svg', u'template']

    >>> matplotlib.rcsetup.all_backends[17]
    u'gdk'

There appears to be a 'backend_gdk' and importing it directly gives the same error.

    >>> import matplotlib.backends.backend_gdk
    Traceback (most recent call last):
      File "<stdin>", line 1, in <module>
      File "/usr/local/lib/python2.7/site-packages/matplotlib/backends/backend_gdk.py", line 33, in <module>
        from matplotlib.backends._backend_gdk import pixbuf_get_pixels_array
    ImportError: No module named _backend_gdk

**Comment by vhernandez** [comment]
It looks like you might have a problem with GTK or matplolib installation. It looks like the module for GTK support in matplotlib was not compiled or not compiled properly. I am testing with older versions of GTK (2.24.7) and matplolib (1.2.1) in OSX Lion installed using homebrew and the GTK support woks well. Could you check that you have GTK+ installed?

**Comment by vhernandez** [comment]
The problem is your installation of matplotlib does not have gtk support compiled. 
I have been testing with homebrew in OSX 10.7 and I managed to run maplotlib with the gtk backgend by installing it using this command:
brew install matplolib --with-pygtk --with-cairo
